# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st

# Title and Description
st.title("My First Streamlit Application")
st.write("Welcome to your starter Streamlit app! This is a simple example demonstrating the basics.")

# Sidebar Input Example
st.sidebar.header("Sidebar Controls")
user_name = st.sidebar.text_input("What's your name?", value="Guest")

# Main Content
st.write(f"Hello, {user_name}! 👋")

# Interactive Widgets Example
number = st.slider("Pick a number", 0, 100, 50)
st.write(f"You picked: {number}")

# Data Display
if st.button("Show sample data"):
    st.write({"A": [1, 2, 3], "B": ["foo", "bar", "baz"]})

# File Uploader Example
uploaded_file = st.file_uploader("Upload a file")
if uploaded_file is not None:
    st.write("File details:", {"filename": uploaded_file.name, "type": uploaded_file.type})

# Plot Example

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)

if st.checkbox("Show sample plot"):
    fig, ax = plt.subplots()
    ax.plot(x, y)
